import type { Metadata } from 'next';
import Link from 'next/link';
import { BlogLayout } from '@/app/blog/BlogLayout';

export const metadata: Metadata = {
  title: 'How to Remove Hidden Metadata from a PDF Before Sharing | Locdone',
  description: 'Every PDF you create contains hidden metadata — your name, organisation, software, and timestamps. Here is how to find it and strip it before sharing a document.',
  alternates: { canonical: 'https://locdone.com/blog/remove-pdf-metadata-before-sharing' },
  openGraph: {
    title: 'How to Remove Hidden Metadata from a PDF Before Sharing',
    description: 'Strip author name, creation date, software info and XMP data from any PDF. Free, locally in your browser.',
  },
};

export default function Post() {
  return (
    <BlogLayout
      title="How to Remove Hidden Metadata from a PDF Before Sharing"
      description="Every PDF you create contains hidden metadata — your name, organisation, software, and timestamps. Here is how to find it and strip it before sharing a document."
      date="2025-06-14"
      readingTime="4 min read"
      tags={['metadata', 'privacy']}
    >
      <div className="space-y-5 text-sm leading-relaxed text-text-secondary md:text-base">
        <p>
          When you save a PDF, the file carries more information than just the visible content. Embedded
          in the file structure is a set of metadata fields that most PDF viewers never show you — but
          that anyone who opens the raw file or uses the right tool can read instantly.
        </p>
        <p>
          Before sharing a document externally, it is worth knowing what you are revealing.
        </p>

        <h2 className="pt-2 font-display text-xl italic text-text-primary">
          What metadata is stored in a PDF
        </h2>
        <p>
          A typical PDF contains two metadata stores: the Info dictionary (a simple key-value store
          in the file) and an XMP stream (an XML-based block that can contain far more detail).
          Together they can include:
        </p>
        <ul className="ml-4 list-disc space-y-1 text-text-secondary">
          <li>
            <strong className="text-text-primary">Author</strong> — the name of the person who
            created or last edited the document, usually pulled from the OS user account
          </li>
          <li>
            <strong className="text-text-primary">Creator and Producer</strong> — the software used
            to create and export the PDF (e.g., Microsoft Word 365, Adobe Acrobat 2023)
          </li>
          <li>
            <strong className="text-text-primary">Creation Date and Modification Date</strong> —
            exact timestamps including timezone
          </li>
          <li>
            <strong className="text-text-primary">Title and Subject</strong> — often auto-populated
            from the document filename or properties
          </li>
          <li>
            <strong className="text-text-primary">Company</strong> — your organisation name, embedded
            by enterprise Office installations
          </li>
          <li>
            <strong className="text-text-primary">XMP fields</strong> — can include document history,
            internal identifiers, and revision information depending on the software
          </li>
        </ul>

        <h2 className="pt-2 font-display text-xl italic text-text-primary">
          Why this matters before you share
        </h2>
        <p>
          Consider a few scenarios where metadata creates an unintended disclosure:
        </p>
        <p>
          <strong className="text-text-primary">Legal documents.</strong> A contract prepared by a
          law firm contains the author field with the drafting associate&apos;s name and the creation
          timestamp. The opposing party can see exactly when the document was created and by whom —
          information that was never meant to be disclosed.
        </p>
        <p>
          <strong className="text-text-primary">Job applications.</strong> A CV exported from Word
          contains your full name in the author field and the company name from your current
          employer&apos;s Office licence — even if you are trying to submit anonymously.
        </p>
        <p>
          <strong className="text-text-primary">Freelance proposals.</strong> A proposal PDF
          contains the creation date, revealing that you put it together in twenty minutes the night
          before the deadline.
        </p>
        <p>
          <strong className="text-text-primary">Healthcare documents.</strong> A referral letter
          generated by practice management software contains internal patient record identifiers in
          the XMP stream.
        </p>

        <h2 className="pt-2 font-display text-xl italic text-text-primary">
          How to see the metadata in a PDF
        </h2>
        <p>
          In Adobe Acrobat: File → Properties → Description tab. In macOS Preview: Tools →
          Show Inspector → the &apos;i&apos; tab. In most PDF readers, there is a Document Properties
          or File Information option.
        </p>
        <p>
          Locdone&apos;s{' '}
          <Link href="/strip-pdf-metadata" className="text-accent hover:underline">
            Strip PDF Metadata tool
          </Link>{' '}
          shows you all the metadata fields it finds in your document before you strip them, so you
          can see exactly what is there.
        </p>

        <h2 className="pt-2 font-display text-xl italic text-text-primary">
          How to strip PDF metadata before sharing
        </h2>
        <ol className="ml-4 list-decimal space-y-1 text-text-secondary">
          <li>
            Open{' '}
            <Link href="/strip-pdf-metadata" className="text-accent hover:underline">
              locdone.com/strip-pdf-metadata
            </Link>
          </li>
          <li>Drop your PDF in — the tool reads and displays all metadata fields found</li>
          <li>Click Strip Metadata to remove the Info dictionary and XMP stream</li>
          <li>Download the clean file</li>
        </ol>
        <p>
          The process runs entirely in your browser. The original file is never uploaded anywhere.
          The stripped file retains all visible content — text, images, formatting — with only the
          hidden metadata removed.
        </p>

        <h2 className="pt-2 font-display text-xl italic text-text-primary">
          Does stripping metadata affect the document?
        </h2>
        <p>
          No. Metadata is separate from document content. Removing it does not change any text,
          image, formatting, or interactive element in the PDF. The file will open and display
          identically — it just will not reveal who created it or when.
        </p>
        <p>
          One edge case: some enterprise document management systems use metadata fields for
          tracking and version control. If you are sharing internally within such a system, check
          whether stripping metadata would break any workflow before doing so.
        </p>
      </div>
    </BlogLayout>
  );
}
